//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.App_Start {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OdontoWeb_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OdontoWeb_Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.App_Start.OdontoWeb_Resources", typeof(OdontoWeb_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail inválido.
        /// </summary>
        internal static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login não cadastrado.
        /// </summary>
        internal static string M0002 {
            get {
                return ResourceManager.GetString("M0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário está inativo.
        /// </summary>
        internal static string M0003 {
            get {
                return ResourceManager.GetString("M0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário está bloqueado. Entre em contato com o administrador do sistema para executar o desbloqueio.
        /// </summary>
        internal static string M0004 {
            get {
                return ResourceManager.GetString("M0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário ja efetuou um login com esta senha provisória. Favor gerar outra senha..
        /// </summary>
        internal static string M0005 {
            get {
                return ResourceManager.GetString("M0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de falhas de login superior ao limite diário de falhas.
        /// </summary>
        internal static string M0006 {
            get {
                return ResourceManager.GetString("M0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credenciais inválidas.
        /// </summary>
        internal static string M0007 {
            get {
                return ResourceManager.GetString("M0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha não pode ser igual à anterior.
        /// </summary>
        internal static string M0008 {
            get {
                return ResourceManager.GetString("M0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha não foi confirmada corretamente.
        /// </summary>
        internal static string M0009 {
            get {
                return ResourceManager.GetString("M0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Senha não pode ficar em branco.
        /// </summary>
        internal static string M0073 {
            get {
                return ResourceManager.GetString("M0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova senha não pode ser em branco.
        /// </summary>
        internal static string M0074 {
            get {
                return ResourceManager.GetString("M0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação da senha não pode ser em branco.
        /// </summary>
        internal static string M0075 {
            get {
                return ResourceManager.GetString("M0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O login não pode ficar em branco.
        /// </summary>
        internal static string M0109 {
            get {
                return ResourceManager.GetString("M0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-Mail não cadastrado.
        /// </summary>
        internal static string M0110 {
            get {
                return ResourceManager.GetString("M0110", resourceCulture);
            }
        }
    }
}
