//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANAMNESE_IMAGEM
    {
        public int ANIM_CD_ID { get; set; }
        public Nullable<int> ANAM_CD_ID { get; set; }
        public string ANIM_NM_NOME { get; set; }
        public string ANIM_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> ANIM_DT_DATA { get; set; }
        public Nullable<int> ANIM_IN_TIPO { get; set; }
        public string ANIM_AQ_ARQUIVO { get; set; }
        public Nullable<int> ANIM_IN_ATIVO { get; set; }
        public Nullable<int> ANIM_IN_ASSINATURA { get; set; }
    
        public virtual ANAMNESE ANAMNESE { get; set; }
    }
}
