//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANAMNESE_NOVA_PERGUNTA
    {
        public int ANNP_CD_ID { get; set; }
        public Nullable<int> ANAM_CD_ID { get; set; }
        public string ANNP_NM_PERGUNTA { get; set; }
        public string ANNP_NM_RESPOSTA { get; set; }
        public Nullable<int> ANNP_IN_ATIVO { get; set; }
    
        public virtual ANAMNESE ANAMNESE { get; set; }
    }
}
