//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRIZ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATRIZ()
        {
            this.FILIAL = new HashSet<FILIAL>();
            this.FORNECEDOR = new HashSet<FORNECEDOR>();
        }
    
        public int MATR_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int TIPE_CD_ID { get; set; }
        public Nullable<int> CRTR_CD_ID { get; set; }
        public string MATR_NM_NOME { get; set; }
        public string MATR_NM_RAZAO { get; set; }
        public string MATR_NR_CNPJ { get; set; }
        public string MATR_NM_EMAIL { get; set; }
        public string MATR_NR_TELEFONES { get; set; }
        public string MATR_NM_CONTATOS { get; set; }
        public string MATR_NM_ENDERECO { get; set; }
        public string MATR_NM_BAIRRO { get; set; }
        public string MATR_NM_CIDADE { get; set; }
        public string MATR_NR_CEP { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public System.DateTime MATR_DT_CADASTRO { get; set; }
        public int MATR_IN_ATIVO { get; set; }
        public string MATR_NR_INSCRICAO_ESTADUAL { get; set; }
        public string MATR_NR_INSCRICAO_MUNICIPAL { get; set; }
        public Nullable<int> MATR_IN_IR_ISENTO { get; set; }
        public string MATR_NR_CNAE { get; set; }
        public string MATR_NM_WEBSITE { get; set; }
        public string MATR_NR_CELULAR { get; set; }
        public string MATR_AQ_LOGOTIPO { get; set; }
        public string MATR_NR_RG { get; set; }
        public string MATR_NR_CPF { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CODIGO_REGIME_TRIBUTARIO CODIGO_REGIME_TRIBUTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILIAL> FILIAL { get; set; }
        public virtual TIPO_PESSOA TIPO_PESSOA { get; set; }
        public virtual UF UF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORNECEDOR> FORNECEDOR { get; set; }
    }
}
