//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAGEM
    {
        public int MENS_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> MENS_DT_DATA { get; set; }
        public string MENS_TX_TEXTO { get; set; }
        public Nullable<int> MENS_CD_AUTOR { get; set; }
        public Nullable<int> MENS_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> MENS_DT_VALIDADE { get; set; }
    }
}
