//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIA_TAG
    {
        public int NOTA_CD_ID { get; set; }
        public int NOTC_CD_ID { get; set; }
        public int TITA_CD_ID { get; set; }
        public string NOTA_NM_NOME_TAG { get; set; }
        public string NOTA_IN_ATIVO { get; set; }
    
        public virtual NOTICIA NOTICIA { get; set; }
        public virtual TIPO_TAG TIPO_TAG { get; set; }
    }
}
