//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORCAMENTO_ANEXO
    {
        public int ORAN_CD_ID { get; set; }
        public Nullable<int> ORCA_CD_ID { get; set; }
        public string ORAN_NM_TITULO { get; set; }
        public Nullable<System.DateTime> ORAN_DT_ANEXO { get; set; }
        public Nullable<int> ORAN_IN_TIPO { get; set; }
        public string ORAN_AQ_ARQUIVO { get; set; }
        public Nullable<int> ORAN_IN_ATIVO { get; set; }
    
        public virtual ORCAMENTO ORCAMENTO { get; set; }
    }
}
