//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORCAMENTO_ACOMPANHAMENTO
    {
        public int ORAC_CD_ID { get; set; }
        public int ORCA_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime ORAC_DT_DATA { get; set; }
        public string ORAC_TX_ACOMPANHAMENTO { get; set; }
        public int ORAC_IN_ATIVO { get; set; }
    
        public virtual ORCAMENTO ORCAMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
