//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORCAMENTO_ITEM
    {
        public int ORIT_CD_ID { get; set; }
        public Nullable<int> ORCA_CD_ID { get; set; }
        public Nullable<int> REDE_CD_ID { get; set; }
        public Nullable<int> TIPR_CD_ID { get; set; }
        public Nullable<decimal> ORIT_VL_OVERRIDE { get; set; }
        public Nullable<int> ORIT_IN_ATIVO { get; set; }
    
        public virtual ORCAMENTO ORCAMENTO { get; set; }
        public virtual REGIAO_DENTE REGIAO_DENTE { get; set; }
        public virtual TIPO_PROCEDIMENTO TIPO_PROCEDIMENTO { get; set; }
    }
}
