//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE()
        {
            this.ANAMNESE = new HashSet<ANAMNESE>();
            this.ORCAMENTO = new HashSet<ORCAMENTO>();
            this.PACIE_NTE_ACOMPANHAMENTO = new HashSet<PACIE_NTE_ACOMPANHAMENTO>();
            this.PACIENTE_ANEXO = new HashSet<PACIENTE_ANEXO>();
            this.PRESCRICAO = new HashSet<PRESCRICAO>();
            this.RECOMENDACAO = new HashSet<RECOMENDACAO>();
            this.PACIENTE_ACOMPANHAMENTO = new HashSet<PACIENTE_ACOMPANHAMENTO>();
            this.PACIENTE_PRESCRICAO = new HashSet<PACIENTE_PRESCRICAO>();
            this.PACIENTE_RECOMENDACAO = new HashSet<PACIENTE_RECOMENDACAO>();
        }
    
        public int PACI_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public string PACI_NM_NOME { get; set; }
        public string PACI_NR_CPF { get; set; }
        public string PACI_NR_RG { get; set; }
        public string PACI_NR_PRONTUARIO { get; set; }
        public Nullable<int> PACI_IN_SEXO { get; set; }
        public string PACI_NR_TELEFONE { get; set; }
        public string PACI_NR_CELULAR { get; set; }
        public string PACI_NR_WHATSAPP { get; set; }
        public string PACI_NM_EMAIL { get; set; }
        public string PACI_NM_ENDERECO { get; set; }
        public string PACI_NM_BAIRRO { get; set; }
        public string PACI_NM_CIDADE { get; set; }
        public Nullable<int> UF_CD_ID { get; set; }
        public string PACI_NR_CEP { get; set; }
        public Nullable<decimal> PACI_VL_SALDO_FINANCEIRO { get; set; }
        public Nullable<int> PACI_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> PACI_DT_CADASTRO { get; set; }
        public Nullable<System.DateTime> PACI_DT_NASCIMENTO { get; set; }
        public string PACI_AQ_FOTO { get; set; }
        public string PACI_TX_OBSERVACOES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANAMNESE> ANAMNESE { get; set; }
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORCAMENTO> ORCAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIE_NTE_ACOMPANHAMENTO> PACIE_NTE_ACOMPANHAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_ANEXO> PACIENTE_ANEXO { get; set; }
        public virtual UF UF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESCRICAO> PRESCRICAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECOMENDACAO> RECOMENDACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_ACOMPANHAMENTO> PACIENTE_ACOMPANHAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_PRESCRICAO> PACIENTE_PRESCRICAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACIENTE_RECOMENDACAO> PACIENTE_RECOMENDACAO { get; set; }
    }
}
