//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_BALANCO_FINANCEIRO
    {
        public int PABF_CD_ID { get; set; }
        public Nullable<int> PACI_CD_ID { get; set; }
        public Nullable<System.DateTime> PABF_DT_MOVIMENTO { get; set; }
        public Nullable<int> PABF_IN_TIPO { get; set; }
        public Nullable<decimal> PABF_VL_VALOR { get; set; }
        public Nullable<int> PABF_IN_ATIVO { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
