//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESCRICAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESCRICAO()
        {
            this.PRESCRICAO_ANEXO = new HashSet<PRESCRICAO_ANEXO>();
        }
    
        public int PRES_CD_ID { get; set; }
        public Nullable<int> PACI_CD_ID { get; set; }
        public Nullable<System.DateTime> PRES_DT_DATA { get; set; }
        public string PRES_NM_NOME { get; set; }
        public string PRES_TX_TEXTO { get; set; }
        public Nullable<int> PRES_IN_ATIVO { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESCRICAO_ANEXO> PRESCRICAO_ANEXO { get; set; }
    }
}
