//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGIAO_DENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGIAO_DENTE()
        {
            this.ORCAMENTO_ITEM = new HashSet<ORCAMENTO_ITEM>();
        }
    
        public int REDE_CD_ID { get; set; }
        public string REDE_NM_NOME { get; set; }
        public string REDE_DS_DESCRICAO { get; set; }
        public Nullable<int> REDE_IN_ATIVO { get; set; }
        public string REDE_AQ_FOTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORCAMENTO_ITEM> ORCAMENTO_ITEM { get; set; }
    }
}
