//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEXO
    {
        public int SEXO_CD_ID { get; set; }
        public string SEXO_SG_SIGLA { get; set; }
        public string SEXO_NM_NOME { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> SEXO_IN_ATIVO { get; set; }
    }
}
