//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_PROCEDIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUB_PROCEDIMENTO()
        {
            this.SUB_PROCEDIMENTO_ANEXO = new HashSet<SUB_PROCEDIMENTO_ANEXO>();
        }
    
        public int SUPR_CD_ID { get; set; }
        public Nullable<int> TIPR_CD_ID { get; set; }
        public string SUPR_NM_NOME { get; set; }
        public string SUPR_SG_SIGLA { get; set; }
        public string SUPR_DS_DESCRICAO { get; set; }
        public Nullable<decimal> SUPR_VL_VALOR { get; set; }
        public Nullable<int> SUPR_VL_PRAZO { get; set; }
        public Nullable<int> SUPR_IN_ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUB_PROCEDIMENTO_ANEXO> SUB_PROCEDIMENTO_ANEXO { get; set; }
        public virtual TIPO_PROCEDIMENTO TIPO_PROCEDIMENTO { get; set; }
    }
}
