//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREFA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAREFA()
        {
            this.TAREFA_ACOMPANHAMENTO = new HashSet<TAREFA_ACOMPANHAMENTO>();
            this.TAREFA_ANEXO = new HashSet<TAREFA_ANEXO>();
            this.TAREFA_NOTIFICACAO = new HashSet<TAREFA_NOTIFICACAO>();
        }
    
        public int TARE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<int> TITR_CD_ID { get; set; }
        public System.DateTime TARE_DT_CADASTRO { get; set; }
        public string TARE_NM_TITULO { get; set; }
        public string TARE_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> TARE_DT_ESTIMADA { get; set; }
        public int TARE_IN_STATUS { get; set; }
        public int TARE_IN_PRIORIDADE { get; set; }
        public int TARE_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> TARE_DT_REALIZADA { get; set; }
        public string TARE_TX_OBSERVACOES { get; set; }
        public string TARE_NM_LOCAL { get; set; }
        public Nullable<int> TARE_IN_AVISA { get; set; }
        public Nullable<int> TARE_CD_USUA_1 { get; set; }
        public Nullable<int> TARE_CD_USUA_2 { get; set; }
        public Nullable<int> TARE_CD_USUA_3 { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREFA_ACOMPANHAMENTO> TAREFA_ACOMPANHAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREFA_ANEXO> TAREFA_ANEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREFA_NOTIFICACAO> TAREFA_NOTIFICACAO { get; set; }
        public virtual TIPO_TAREFA TIPO_TAREFA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual USUARIO USUARIO2 { get; set; }
        public virtual USUARIO USUARIO3 { get; set; }
        public virtual ASSINANTE ASSINANTE { get; set; }
    }
}
