//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONE
    {
        public int TELE_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> CATE_CD_ID { get; set; }
        public string TELE_NM_NOME { get; set; }
        public string TELE_NR_TELEFONE { get; set; }
        public string TELE_NR_CELULAR { get; set; }
        public string TELE_NR_WHATSAPP { get; set; }
        public string TELE_NM_EMAIL { get; set; }
        public Nullable<int> TELE_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CATEGORIA_TELEFONE CATEGORIA_TELEFONE { get; set; }
    }
}
