//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PROCEDIMENTO_ANEXO
    {
        public int TPAN_CD_ID { get; set; }
        public Nullable<int> TIPR_CD_ID { get; set; }
        public string TPAN_NM_TITULO { get; set; }
        public Nullable<int> TPAN_IN_TIPO { get; set; }
        public Nullable<System.DateTime> TPAN_DT_ANEXO { get; set; }
        public string TPAN_AQ_ARQUIVO { get; set; }
        public Nullable<int> TPAN_IN_ATIVO { get; set; }
    
        public virtual TIPO_PROCEDIMENTO TIPO_PROCEDIMENTO { get; set; }
    }
}
