//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PROCEDIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_PROCEDIMENTO()
        {
            this.ORCAMENTO_ITEM = new HashSet<ORCAMENTO_ITEM>();
            this.TIPO_PROCEDIMENTO_ANEXO = new HashSet<TIPO_PROCEDIMENTO_ANEXO>();
        }
    
        public int TIPR_CD_ID { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public string TIPR_NM_NOME { get; set; }
        public string TIPR_SG_SIGLA { get; set; }
        public string TIPR_DS_DESCRICAO { get; set; }
        public int TIPR_IN_ATIVO { get; set; }
        public Nullable<decimal> TIPR_VL_VALOR { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORCAMENTO_ITEM> ORCAMENTO_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_PROCEDIMENTO_ANEXO> TIPO_PROCEDIMENTO_ANEXO { get; set; }
    }
}
