//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_REMUNERACAO
    {
        public int USRE_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> USRE_DT_REFERENCIA { get; set; }
        public Nullable<decimal> USRE_VL_VALOR_FIXO { get; set; }
        public Nullable<decimal> USRE_VL_TAREFAS { get; set; }
        public Nullable<decimal> USRE_VL_PRODUCAO { get; set; }
        public Nullable<decimal> USRE_VL_PREMIO { get; set; }
        public Nullable<decimal> USRE_VL_AVAL_EQUIPE { get; set; }
        public Nullable<decimal> USRE_VL_AVAL_PACIENTES { get; set; }
        public Nullable<decimal> USRE_VL_CONVERSAO { get; set; }
        public Nullable<int> USRE_IN_ATIVO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
